# Generated by Django 4.1.3 on 2023-02-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0008_pendings_office'),
    ]

    operations = [
    ]
