# Generated by Django 4.1.3 on 2023-02-08 16:04

from django.db import migrations

def remove_bad_data(apps, schema_editor):
    Pendings = apps.get_model('appsmartip', 'Pendings')
    Pendings.objects.filter(office__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0006_alter_pendings_options_pendings_office'),
    ]

    operations = [
        migrations.RunPython(remove_bad_data),
    ]
