# Generated by Django 4.1.3 on 2023-01-25 12:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devusers',
            old_name='message_acount',
            new_name='message_account',
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devtype',
            name='dev_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='edifice',
            name='edifice',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendings',
            name='reason',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
