# Generated by Django 4.1.3 on 2022-11-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0003_model_dev_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='model',
            name='dev_type',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appsmartip.brand'),
            preserve_default=False,
        ),
    ]
