# Generated by Django 4.1.3 on 2023-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0003_model_img_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devusers',
            name='cuil',
            field=models.CharField(default='20309003749', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devusers',
            name='observations',
            field=models.TextField(default='Sin Observaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='mapping',
            field=models.TextField(default='Segundo piso al lado de la cocina del federal 2'),
            preserve_default=False,
        ),
    ]
