# Generated by Django 4.1.3 on 2023-02-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0004_devusers_cuil_devusers_observations_office_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsmartip.devusers'),
        ),
    ]
