# Generated by Django 4.1.3 on 2023-02-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartip', '0005_alter_device_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendings',
            options={'ordering': ['-date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='pendings',
            name='office',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='appsmartip.office'),
            preserve_default=False,
        ),
    ]
